# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='edit_status_time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
