# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0002_edit_edit_status_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='edit_status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Waiting')]),
        ),
        migrations.AlterField(
            model_name='edit',
            name='edit_type',
            field=models.IntegerField(choices=[(0, 'Modify'), (1, 'Add'), (2, 'Delete')]),
        ),
    ]
