# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0003_auto_20170930_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edit_meta',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
